### ISSUE TITLE
idea: check service credentials

### ISSUE THREAD

**Issue by GregWhiteDBA** [devondba/SQLServerSecurityAudit#2]
check to see if using standard NT AUTHORITY\SYSTEM to run the sql service / agent etc.

**Comment by devondba** [comment]
Will write that one shortly, cheers.

**Comment by devondba** [comment]
select *
FROM sys.dm_server_services 

should be named account etc, not NT Service\MSSQLSERVER

**Comment by devondba** [comment]
included
