### ISSUE TITLE
idea: check for use of DAC

### ISSUE THREAD

**Issue by GregWhiteDBA** [devondba/SQLServerSecurityAudit#6]
check and return if dedicated admin console is enabled

**Comment by devondba** [comment]
I thought about this one but I think it's something more for ensuring you can connect rather than a security concern so I'm not sure if it's vaild this script set. It's already in sp_Blitz and I'm trying not to cross that way too much, only for the specifc secutity elements.

**Comment by devondba** [comment]
Have added in with the other config checks.
