### ISSUE TITLE
idea: check logging level auditing

### ISSUE THREAD

**Issue by GregWhiteDBA** [devondba/SQLServerSecurityAudit#7]
will be none / failed / successful / both

guess should warn if none

**Comment by devondba** [comment]
Totally agree....

EXEC xp_instance_regread N'HKEY_LOCAL_MACHINE', N'Software\Microsoft\MSSQLServer\MSSQLServer', N'AuditLevel'

Will show current audit level 1 = none, 2 = failed logins only so value must be above 1

**Comment by devondba** [comment]
added in with alerts for none or successful only.
