### ISSUE TITLE
idea: allow remote connections to this server

### ISSUE THREAD

**Issue by GregWhiteDBA** [devondba/SQLServerSecurityAudit#8]
this is an allow remote connections to this server is off by default but should show if on as i have had reasons to enable this.

**Comment by devondba** [comment]
On thinking about this one, it's probably good to check all the relevant security items in sys.configurations

Probably start with the following

SELECT name, value, value_in_use
FROM [sys].configurations
WHERE [name] in (
	'cross db ownership chaining'--0
 ,	'remote access'--0
 ,	'show advanced options'--0
 ,	'remote proc trans'--0
 ,	'remote admin connections'--1
 ,	'common criteria compliance enabled'--1
 ,	'filestream access level'--0
 ,	'Agent XPs'--0
 ,	'Database Mail XPs'--0
 ,	'SMO and DMO XPs'--0
 ,	'xp_cmdshell'--0
 ,	'default trace enabled'--1
 ,	'contained database authentication' --info
 )

**Comment by devondba** [comment]
Adding two sections, one to show info, one to show bad config.
